# Generated by Django 5.1.1 on 2024-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
