# Generated by Django 5.0.6 on 2024-10-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='imageCaregiver',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver/'),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='imageElder',
            field=models.ImageField(blank=True, null=True, upload_to='Elder/'),
        ),
    ]
