# Generated by Django 5.0.6 on 2024-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0002_remove_caregiverprofile_license_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='elderprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
