# Generated by Django 5.0.6 on 2024-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0002_rename_imagecaregiver_caregiverprofile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverprofile',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='elderprofile',
            old_name='name',
            new_name='username',
        ),
    ]
