# Generated by Django 5.0.6 on 2024-10-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0003_rename_user_caregiverprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
