# Generated by Django 5.1.2 on 2024-10-12 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0003_caregiverprofile_caregiver_elderprofile_elder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elderprofile',
            name='Elder',
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='elder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
