# Generated by Django 5.0.6 on 2024-10-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0003_rename_name_caregiverprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverprofile',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='elderprofile',
            old_name='username',
            new_name='name',
        ),
    ]
