# Generated by Django 5.0.6 on 2024-10-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0005_caregiverprofile_created_by_elderprofile_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='elderprofile',
            name='created_by',
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='Caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='Elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
