# Generated by Django 5.0.6 on 2024-10-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldercareapp', '0004_remove_elderprofile_elder_elderprofile_elder'),
        ('eldercareapp', '0006_remove_caregiverprofile_created_by_and_more'),
    ]

    operations = [
    ]
